### ISSUE TITLE
Summarize Article Text Using Services or Libraries

### ISSUE THREAD

**Issue by armintalaie** [ubclaunchpad/Essentially#14]
### Acceptance Criteria
generate summary

**Comment by armintalaie** [comment]
@ymnglli  @ryanmckim @sauravbanna @Hgjnnf what's the status on this

**Comment by ymnglli** [comment]
I'm having a little trouble converting the model to ONNX + quantizing, which is what I was hoping we could get done by Phase 1. If it doesn't get fixed by the deadline, I'll push the simplified summarizer without optimizations!

**Comment by ymnglli** [comment]
Also, I'll be uploading the notebook sometime today so you can see what I'm talking about.

**Comment by armintalaie** [comment]
@ymnglli  sounds good. let me know when it's up so I can take a look

**Comment by ymnglli** [comment]
its up! On the optimization branch

**Comment by armintalaie** [comment]
missing API calls (flask setup + call to python api from node backend)
@ymnglli @Hgjnnf , who is implementing it?

**Comment by Hgjnnf** [comment]
> missing API calls (flask setup + call to python api from node backend)
> 
> @ymnglli @Hgjnnf , who is implementing it? 
> 
> 

@armintalaie I'm doing it.
