### ISSUE TITLE
Implement Summary Endpoint

### ISSUE THREAD

**Issue by armintalaie** [ubclaunchpad/Essentially#25]
`/article/summary`

the above endpoint will be called from the extension. in turn with the request this endpoint, internally, will call the python API to summarize. the API should handle all cases that the frontend will send. e.g. empty text, timing out in case it takes too long, etc.

task is to document the cases and implement them in the backend directory. if you're unsure about a certain thing message one of the developers.

**Comment by sauravbanna** [comment]
Solved by #40
