### ISSUE TITLE
Pop up Data (meta information)

### ISSUE THREAD

**Issue by armintalaie** [ubclaunchpad/Essentially#51]
Include the meta information in the extension 
related to#50 

## Acceptance criteria
implement the figma designs to display:
- title
- author
- date

**Comment by armintalaie** [comment]
@Michaeltaoma can you do this one? Since your update extracts these already and we already show the date and title. only need to add author now

**Comment by Michaeltaoma** [comment]
> @Michaeltaoma can you do this one? Since your update extracts these already and we already show the date and title. only need to add author now

Sure, is this one require me to do a Figma design or implement the front end? I am a bit confused.

**Comment by armintalaie** [comment]
> > @Michaeltaoma can you do this one? Since your update extracts these already and we already show the date and title. only need to add author now
> 
> Sure, is this one require me to do a Figma design or implement the front end? I am a bit confused.

believe there some figma frames that have that design 9basically keywords left, author and date right)
so it's some small FE and CSS code. since the font size and margin might look too small or something on the extension. feel free to play around with those to implement what makes sense
